### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by harleykin** [aredridel/webring#9]
Looks great!  If I may make a suggestion, perhaps have your site enforce HTTPS from HTTP?  I noticed while surfing through the ring that any sites still using the older HTTP links instead of HTTPS might get hung up when visitors click previous and next.  (I hope that made sense!)  It's easy enough for me to fix by adding the missing 's' in the URL but not all visitors may be tech savvy enough to spot that.

Maybe via HTACCESS file or something?

This is what I use:

> RewriteEngine On 
> RewriteCond %{HTTPS} off 
> RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

Thanks again for running this and sharing with the digital world!  :D

**Comment by harleykin** [comment]
OK I take it back ... seems only this one is having the issue: https://webring.dinhe.net/prev/https://fanlistings.nickifaulk.com/alabama/

Other link (next) works just fine?

**Comment by aredridel** [comment]
Hm. I don't think that's https related — but matching the database without the protocol might be useful so that people can switch to https easily. Let me see if I can figure out what's up there!

**Comment by aredridel** [comment]
Oh! Found it, fixed in 80b747482. Deploying the fix now.

**Comment by harleykin** [comment]
You're so awesome.  :3

**Comment by aredridel** [comment]
As far as enforcing HTTPS, I don't actually want to: it's a barrier to entry, and while it prevents people from snooping a bit on what one reads as a viewer, VPNs prevent that better. Lots of sites don't need it, and there's a real technical cost to maintaining it. It's not invisible yet!

**Comment by harleykin** [comment]
Understandable :)
